# Generated by Django 3.2.4 on 2021-06-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lang',
        ),
        migrations.AddField(
            model_name='user',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
